### PR TITLE
additional pdo attributes

### PR DESCRIPTION
**Pull request by agolebiowska**
Without this two PDO attributes everything is returns as a string... or maybe I skip something important? Please, correct me if I'm wrong, but for now I can't write any code without overwriting this file. Btw Atlas is a great tool :)

### CODE REVIEW

**Comment by froschdesign** [comment]
@agolebiowska 
> but for now I can't write any code without overwriting this file.

No need to overwrite. You can use:

```php
$pdo = new PDO(…);
$pdo->setAttribute(…);

$connection = Atlas\Pdo\Connection::new($pdo);
// or
$connection = new Atlas\Pdo\Connection($pdo);
// or
$connection = (Atlas\Pdo\Connection::factory($pdo))();
```
or
```php
$connection = Atlas\Pdo\Connection::new(…);
$connection->getPdo()->setAttribute(…);
```

**Comment by agolebiowska** [comment]
Yeah I understand, but in my case still needs to have some kind of wrapper, to simply inject my custom atlas connection without repeating myself. I am more interested why this is not by default? Shouldn't it be at least mentioned in the docs? I was really confused when it turns out that there is no type mapping :)

**Comment by pmjones** [comment]
> "Btw Atlas is a great tool :)"

Thanks for saying. :-)

> "why this is not by default?"

The short answer is, "some people's defaults are not other people's defaults." Some folks *need* emulated prepares and stringified fetches, for legacy reasons if no other.

The Atlas PDO connection overrides exactly and only the one thing it needs so it can operate consistently *for its own purposes*; that is, using exceptions instead of warnings or silencing errors.

Now, having said that, you need to create a PDO instance of your own anyway, when creating a Connection; as @froschdesign points out, it is a trivial exercise to set the attributes on that instance before you pass it to the Atlas Connection object.

Alternatively, here is an example using the Connection::new() method that sets the attributes:

```php
$connection = Connection::new('sqlite::memory', null, null, [
    PDO::ATTR_EMULATE_PREPARES => false,
    PDO::ATTR_STRINGIFY_FETCHES => false,
]);
```

Does that begin to help?

**Comment by agolebiowska** [comment]
Thanks for your explanation! In that case, I'll use this as you recommend.

**Pull request closed without merging**
